### ISSUE TITLE
아키텍처 및 패키지 구조 정의

### ISSUE THREAD

**Issue by JJongmen** [ERICA-gamsung/android#8]
## Kind (Required)

Choose the suitable template if exists.

- Bug report (please use the other template)
- **Proposal / Discussion**
- Improvement
- Other

## Overview (Required)

- 아키텍처 정의
- 패키지 구조 정의

## Links

- X

**Comment by johnhuh619** [comment]
- core.presentation
- feature.presentation
  - data
  - domain
  - presentation
  - utils
- di

**Comment by JJongmen** [comment]
![image](https://github.com/ERICA-gamsung/android/assets/55042337/690c7b92-15f8-444d-85d5-8418d1930bbc)
UI 레이어 : 화면에 애플리케이션 데이터를 표시
도메인 레이어 : UI와 데이터 레이어 간의 상호작용을 간소화하고 재사용
데이터 레이어 : 앱의 비즈니스 로직을 포함하고 애플리케이션 데이터를 노출
[출처](https://developer.android.com/topic/architecture?hl=ko)

**Comment by johnhuh619** [comment]
Ui layer 는 다음과 같은 구조를 지닌다.
- Ui layer
  - UiState
  - UiEvent
  - ViewModel
  
![image](https://github.com/ERICA-gamsung/android/assets/55565839/8abe5364-7f60-4afc-86ce-a1b14010fc4f)
![image](https://github.com/ERICA-gamsung/android/assets/55565839/77c4b01c-3d9e-410e-a9a7-b951c3ef4654)
